name: assignment_tutorbin
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  expansion_tile_card: ^2.0.0


flutter:

  assets:
    - images/

  uses-material-design: true


flutter_icons:
  image_path: "icon/logo.png"
  android: true

